### ISSUE TITLE
Error with /reports/getSharePointSiteUsageDetail Graph Endpoint

### ISSUE THREAD

**Issue by warwickbuilds** [joerodgers/Copilot-Document-Sharing-Report#1]
Do you know if there is an issue with this endpoint, I get the error in multiple tenants

Error: Exception calling "Where" with "2" argument(s): "Value cannot be null. (Parameter 'source')"

- Using Delegated Auth, Reports.Read.All access is granted for the API permissions
- Graph Explorer errors also
- it seems to know about this endpoint https://graph.microsoft.com/v1.0/reports/microsoft.graph.getSharePointSiteUsageDetail(period='D180')

UPDATE
- got it to work in graph explorer in Tenant1 by again giving consent for Reports.Read.All via permissions tab
- Tenant2 it doesn't work still, even with Reports.Read.All having consent in permissions tab

UPDATE 2
- Got it working by assigning the Report Reader m365 permissions, I only had Global Reader, it would have worked ok with Global Admin by itself
- So now it's just the JSON parameter deprecation 

**PS: Love the scripts and the methods they use to get data!!!**

**Comment by warwickbuilds** [comment]
also getting this error with the json parameter

 | {"Message":"JSON format is not supported."} 

removing the from the invoke call - gets past it, now sure the impact

**Comment by warwickbuilds** [comment]
also getting this error with the json parameter

 | {"Message":"JSON format is not supported."} 

removing the from the invoke call - gets past it
seems to have an impact removing JSON

VERBOSE: 08/01/2024 13:38:09 - Downloading SharePoint usage details
Invoke-PnPGraphMethod: 
Line |
 174 |  … geDetails = Invoke-PnPGraphMethod -Method Get -Url $usageReportUrl -A …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 'R' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.


UPDATE: 
- adding the $format back in seems to work fine now, and I see is required
- But still getting the R issue no matter what I try
- I think it may be a API issue

**Comment by warwickbuilds** [comment]
Ok I got it working by changing the following

Changing to a Invoke-RestMethod

```
        $accessToken = Get-PnPAccessToken
        $headers = @{
            "Authorization" = "Bearer $accessToken"
            "Accept"        = "application/json"
        }
    

        # pull site usage details report
        $response = Invoke-RestMethod -Uri $usageReportUrl -Headers $headers -Method Get
        $siteUsageDetails = $response.value | ConvertTo-Json
```


Next error was with [Linq.Enumerable]::Where 

Changed to 

```
$siteUsageDetail = $siteUsageDetails | Where-Object { $_.SiteId -eq $sharedDocumentSiteSummaryModel.SiteId } | Select-Object -First 1
if ($siteUsageDetail) {
    $sharedDocumentSiteSummaryModel.ActiveFileCount  = $siteUsageDetail.activeFileCount 
    $sharedDocumentSiteSummaryModel.LastActivityDate = $siteUsageDetail.lastActivityDate
    $sharedDocumentSiteSummaryModel.PageViewCount    = $siteUsageDetail.pageViewCount  
    $sharedDocumentSiteSummaryModel.SiteFileCount    = $siteUsageDetail.fileCount 
    $sharedDocumentSiteSummaryModel.VisitedPageCount = $siteUsageDetail.visitedPageCount
}
```

**Comment by joerodgers** [comment]
@warwickbuilds, what version of the PnP.PowerShell module and PowerShell (```$PSVersionTable```) are you using? I've had dozens of customers run these scripts, this is the first time I'm seeing either of these two errors.

I use ```[Linq.Enumerable]::Where ``` because it performs better on larger (100k+) datasets, the substituted code is a native PowerShell workaround and will work just as well on smaller tenants.

**Comment by warwickbuilds** [comment]
Hi Thanks for the reply

- Running PowerShell v7.4.3 and PnP.Powershell 2.0.3 (Windows 11, VS Code)

- Good to know the reason for the [Linq.Enumerable]::Where
Has this been deprecated in PS 7+ maybe or required additional prerequisites

- Not sure why the PNP REST call wasn't returning JSON

**Comment by joerodgers** [comment]
@warwickbuilds, I've completed testing with PowerShell 7.4.4 and PnP.PowerShell v2.3.0 and couldn't repo the issue.  Have you tried out running outside of VSCode, using a native PowerShell 7.x console window?  

The _Script Analysis_ option in the PowerShell extension may force assemblies to load into the current app domain despite the owning module not being imported, which may be causing the Linq issue.

**Comment by warwickbuilds** [comment]
Good to know, I'll test again in the future when needed.

Thanks again for sharing, top scripting!!
